export const JobsData = [
  {
    jobTitle: "Software Engineer",
    companyName: "Tech Solutions Inc.",
    salary: "$85,000/year",
    location: "New York, NY",
    level: "Mid-Level",
  },
  {
    jobTitle: "Marketing Specialist",
    companyName: "Creative Marketing Co.",
    salary: "$60,000/year",
    location: "San Francisco, CA",
    level: "Entry-Level",
  },
  {
    jobTitle: "Data Analyst",
    companyName: "DataWorks",
    salary: "$70,000/year",
    location: "Austin, TX",
    level: "Mid-Level",
  },
  {
    jobTitle: "Product Manager",
    companyName: "Innovatech",
    salary: "$95,000/year",
    location: "Seattle, WA",
    level: "Senior-Level",
  },
  {
    jobTitle: "UX Designer",
    companyName: "Design Hub",
    salary: "$78,000/year",
    location: "Chicago, IL",
    level: "Mid-Level",
  },
  {
    jobTitle: "Sales Associate",
    companyName: "RetailPro",
    salary: "$50,000/year",
    location: "Los Angeles, CA",
    level: "Entry-Level",
  },
  {
    jobTitle: "Human Resources Manager",
    companyName: "People First Corp.",
    salary: "$88,000/year",
    location: "Denver, CO",
    level: "Senior-Level",
  },
  {
    jobTitle: "Network Administrator",
    companyName: "IT Solutions Ltd.",
    salary: "$82,000/year",
    location: "Dallas, TX",
    level: "Mid-Level",
  },
  {
    jobTitle: "Content Writer",
    companyName: "StoryMakers",
    salary: "$55,000/year",
    location: "Portland, OR",
    level: "Entry-Level",
  },
  {
    jobTitle: "Financial Analyst",
    companyName: "FinancePros",
    salary: "$90,000/year",
    location: "Boston, MA",
    level: "Mid-Level",
  },
];
